/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.admin;

import ObjekClass.Keluarga;
import ui.welcome.*;

/**
 *
 * @author Zidan
 */
public class form_manajemen extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public form_manajemen() {
        initComponents();
    }
    public void empty_data() {
        field_nokk.setText("");
        field_kepkel.setText("");
        field_ibu.setText("");
        field_anak3.setText("");
        field_anak2.setText("");
        field_anak1.setText("");
        field_alamat.setText("");
    }
    Keluarga family = new Keluarga();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_posisi = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_manaj = new javax.swing.JLabel();
        btn_datart = new javax.swing.JLabel();
        Label_alamat3 = new javax.swing.JLabel();
        btn_keluarga = new javax.swing.JLabel();
        btn_silsi = new javax.swing.JLabel();
        btn_logout = new javax.swing.JLabel();
        logo_mini = new javax.swing.JLabel();
        Label_NIK = new javax.swing.JLabel();
        Label_nama = new javax.swing.JLabel();
        Label_namapanggil = new javax.swing.JLabel();
        Label_Anak3 = new javax.swing.JLabel();
        field_nokk = new javax.swing.JTextField();
        field_kepkel = new javax.swing.JTextField();
        field_ibu = new javax.swing.JTextField();
        field_anak1 = new javax.swing.JTextField();
        field_anak2 = new javax.swing.JTextField();
        field_anak3 = new javax.swing.JTextField();
        field_alamat = new javax.swing.JTextField();
        Label_Anak2 = new javax.swing.JLabel();
        Label_Anak1 = new javax.swing.JLabel();
        btn_resetform = new javax.swing.JButton();
        btn_insert = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        dashboardkiri = new javax.swing.JLabel();
        panel_menu = new javax.swing.JLabel();
        bgkota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Penduduk");
        setLocation(new java.awt.Point(350, 80));

        jPanel1.setBackground(new java.awt.Color(0, 0, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_manaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Button/btn_manaj1.png"))); // NOI18N
        btn_manaj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(btn_manaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 280, -1));

        btn_datart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Button/btn_dataRT.png"))); // NOI18N
        btn_datart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_datart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_datartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_datartMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_datartMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_datartMouseReleased(evt);
            }
        });
        jPanel1.add(btn_datart, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 280, -1));

        Label_alamat3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_alamat3.setForeground(new java.awt.Color(255, 255, 255));
        Label_alamat3.setText("Alamat");
        jPanel1.add(Label_alamat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 580, -1, -1));

        btn_keluarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Button/btn_kel.png"))); // NOI18N
        btn_keluarga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_keluarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_keluargaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_keluargaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_keluargaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_keluargaMouseReleased(evt);
            }
        });
        jPanel1.add(btn_keluarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 280, -1));

        btn_silsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Button/btn_silsi.png"))); // NOI18N
        btn_silsi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_silsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_silsiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_silsiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_silsiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_silsiMouseReleased(evt);
            }
        });
        jPanel1.add(btn_silsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 280, -1));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Button/btn_logout.png"))); // NOI18N
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_logoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_logoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_logoutMouseReleased(evt);
            }
        });
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 280, -1));

        logo_mini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_mini.png"))); // NOI18N
        jPanel1.add(logo_mini, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        Label_NIK.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_NIK.setForeground(new java.awt.Color(255, 255, 255));
        Label_NIK.setText("No. Kartu Keluarga");
        jPanel1.add(Label_NIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        Label_nama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_nama.setForeground(new java.awt.Color(255, 255, 255));
        Label_nama.setText("Kepala Keluarga");
        jPanel1.add(Label_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        Label_namapanggil.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_namapanggil.setForeground(new java.awt.Color(255, 255, 255));
        Label_namapanggil.setText("Ibu");
        jPanel1.add(Label_namapanggil, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        Label_Anak3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_Anak3.setForeground(new java.awt.Color(255, 255, 255));
        Label_Anak3.setText("Anak ke - 3");
        jPanel1.add(Label_Anak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, -1, -1));

        field_nokk.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_nokk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_nokk.setBorder(null);
        field_nokk.setPreferredSize(new java.awt.Dimension(415, 50));
        jPanel1.add(field_nokk, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 780, 40));

        field_kepkel.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_kepkel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_kepkel.setBorder(null);
        field_kepkel.setPreferredSize(new java.awt.Dimension(415, 50));
        field_kepkel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_kepkelActionPerformed(evt);
            }
        });
        jPanel1.add(field_kepkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 780, 40));

        field_ibu.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_ibu.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_ibu.setBorder(null);
        field_ibu.setPreferredSize(new java.awt.Dimension(415, 50));
        jPanel1.add(field_ibu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 780, 40));

        field_anak1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_anak1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_anak1.setBorder(null);
        field_anak1.setPreferredSize(new java.awt.Dimension(415, 50));
        jPanel1.add(field_anak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, -1, 40));

        field_anak2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_anak2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_anak2.setBorder(null);
        field_anak2.setPreferredSize(new java.awt.Dimension(415, 50));
        jPanel1.add(field_anak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, 40));

        field_anak3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_anak3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_anak3.setBorder(null);
        field_anak3.setPreferredSize(new java.awt.Dimension(415, 50));
        jPanel1.add(field_anak3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, -1, 40));

        field_alamat.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        field_alamat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        field_alamat.setBorder(null);
        field_alamat.setPreferredSize(new java.awt.Dimension(415, 50));
        jPanel1.add(field_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, -1, 40));

        Label_Anak2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_Anak2.setForeground(new java.awt.Color(255, 255, 255));
        Label_Anak2.setText("Anak ke - 2");
        jPanel1.add(Label_Anak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, -1, -1));

        Label_Anak1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Label_Anak1.setForeground(new java.awt.Color(255, 255, 255));
        Label_Anak1.setText("Anak ke - 1");
        jPanel1.add(Label_Anak1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        btn_resetform.setBackground(new java.awt.Color(241, 196, 15));
        btn_resetform.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_resetform.setForeground(new java.awt.Color(255, 255, 255));
        btn_resetform.setText("Reset Form");
        btn_resetform.setBorder(null);
        btn_resetform.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_resetform.setPreferredSize(new java.awt.Dimension(160, 50));
        btn_resetform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_resetformMouseClicked(evt);
            }
        });
        jPanel1.add(btn_resetform, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 160, 90));

        btn_insert.setBackground(new java.awt.Color(39, 174, 96));
        btn_insert.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_insert.setForeground(new java.awt.Color(255, 255, 255));
        btn_insert.setText("Insert");
        btn_insert.setBorder(null);
        btn_insert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_insert.setPreferredSize(new java.awt.Dimension(160, 50));
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });
        jPanel1.add(btn_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 380, -1, 90));

        btn_update.setBackground(new java.awt.Color(0, 151, 230));
        btn_update.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.setBorder(null);
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.setPreferredSize(new java.awt.Dimension(160, 50));
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, -1, 90));

        btn_delete.setBackground(new java.awt.Color(232, 65, 24));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.setBorder(null);
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.setPreferredSize(new java.awt.Dimension(160, 50));
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 490, -1, 90));

        dashboardkiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg_dashboardkiri.png"))); // NOI18N
        jPanel1.add(dashboardkiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/panel_menu.png"))); // NOI18N
        jPanel1.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        bgkota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bg_adminuserkota.png"))); // NOI18N
        jPanel1.add(bgkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_datartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datartMouseEntered
        // TODO add your handling code here:
        btn_datart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_dataRT1.png")));
    }//GEN-LAST:event_btn_datartMouseEntered

    private void btn_datartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datartMouseExited
        // TODO add your handling code here:
        btn_datart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_dataRT.png")));
    }//GEN-LAST:event_btn_datartMouseExited

    private void btn_datartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datartMousePressed
        // TODO add your handling code here:
        btn_datart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_dataRT2.png")));

        this.dispose();
        new ui.admin.form_dataper_rt().setVisible(true);
    }//GEN-LAST:event_btn_datartMousePressed

    private void btn_datartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_datartMouseReleased
        // TODO add your handling code here:
        btn_datart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_dataRT1.png")));
    }//GEN-LAST:event_btn_datartMouseReleased

    private void btn_keluargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluargaMouseEntered
        // TODO add your handling code here:
        btn_keluarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_kel1.png")));
    }//GEN-LAST:event_btn_keluargaMouseEntered

    private void btn_keluargaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluargaMouseExited
        // TODO add your handling code here:
        btn_keluarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_kel.png")));
    }//GEN-LAST:event_btn_keluargaMouseExited

    private void btn_keluargaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluargaMousePressed
        // TODO add your handling code here:
        btn_keluarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_kel2.png")));

        this.dispose();
        new ui.admin.form_datakeluarga().setVisible(true);
    }//GEN-LAST:event_btn_keluargaMousePressed

    private void btn_keluargaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_keluargaMouseReleased
        // TODO add your handling code here:
        btn_keluarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_kel1.png")));
    }//GEN-LAST:event_btn_keluargaMouseReleased

    private void btn_silsiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_silsiMouseEntered
        // TODO add your handling code here:
        btn_silsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_silsi1.png")));
    }//GEN-LAST:event_btn_silsiMouseEntered

    private void btn_silsiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_silsiMouseExited
        // TODO add your handling code here:
        btn_silsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_silsi.png")));
    }//GEN-LAST:event_btn_silsiMouseExited

    private void btn_silsiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_silsiMousePressed
        // TODO add your handling code here:
        btn_silsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_silsi2.png")));

        this.dispose();
        new ui.admin.form_silsilah().setVisible(true);
    }//GEN-LAST:event_btn_silsiMousePressed

    private void btn_silsiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_silsiMouseReleased
        // TODO add your handling code here:
        btn_silsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_silsi1.png")));
    }//GEN-LAST:event_btn_silsiMouseReleased

    private void btn_logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseEntered
        // TODO add your handling code here:
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_logout1.png")));
    }//GEN-LAST:event_btn_logoutMouseEntered

    private void btn_logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseExited
        // TODO add your handling code here:
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_logout.png")));
    }//GEN-LAST:event_btn_logoutMouseExited

    private void btn_logoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMousePressed
        // TODO add your handling code here:
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_logout2.png")));

        this.dispose();
        new ui.welcome.login().setVisible(true);
    }//GEN-LAST:event_btn_logoutMousePressed

    private void btn_logoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseReleased
        // TODO add your handling code here:
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/button/btn_logout1.png")));
    }//GEN-LAST:event_btn_logoutMouseReleased

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        family.setNomorKK(field_nokk.getText());
        family.setKepalaKeluarga(field_kepkel.getText());
        family.setIbu(field_ibu.getText());
        family.setAnak1(field_anak1.getText());
        family.setAnak2(field_anak2.getText());
        family.setAnak3(field_anak3.getText());
        family.setAlamat(field_alamat.getText());
        family.simpan();
       
    }//GEN-LAST:event_btn_insertActionPerformed

    private void btn_resetformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetformMouseClicked
        empty_data();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetformMouseClicked

    private void field_kepkelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_kepkelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_kepkelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_manajemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_manajemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_manajemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_manajemen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_manajemen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Anak1;
    private javax.swing.JLabel Label_Anak2;
    private javax.swing.JLabel Label_Anak3;
    private javax.swing.JLabel Label_NIK;
    private javax.swing.JLabel Label_alamat3;
    private javax.swing.JLabel Label_nama;
    private javax.swing.JLabel Label_namapanggil;
    private javax.swing.JLabel bgkota;
    private javax.swing.JLabel btn_datart;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_insert;
    private javax.swing.JLabel btn_keluarga;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_manaj;
    private javax.swing.JButton btn_resetform;
    private javax.swing.JLabel btn_silsi;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel dashboardkiri;
    private javax.swing.JTextField field_alamat;
    private javax.swing.JTextField field_anak1;
    private javax.swing.JTextField field_anak2;
    private javax.swing.JTextField field_anak3;
    private javax.swing.JTextField field_ibu;
    private javax.swing.JTextField field_kepkel;
    private javax.swing.JTextField field_nokk;
    private javax.swing.ButtonGroup group_posisi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo_mini;
    private javax.swing.JLabel panel_menu;
    // End of variables declaration//GEN-END:variables
}
