/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.welcome;

import ObjekClass.User;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Zidan
 */
public class regis extends javax.swing.JFrame {

    public regis() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    User data = new User();

    public void empty_data() {
        User_Field.setText("");
        Pass_Field.setText("");
        PassConf_Field.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpassword = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Keluarga = new javax.swing.JLabel();
        Informasi = new javax.swing.JLabel();
        Btn_Regis = new javax.swing.JButton();
        User_Field = new javax.swing.JTextField();
        Pass_Field = new javax.swing.JPasswordField();
        PassConf_Field = new javax.swing.JPasswordField();
        Lbl_Masuk = new javax.swing.JLabel();
        Ulang_password = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        belumpunyaakun = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        txtpassword.setFont(new java.awt.Font("Anonymous Pro", 0, 18)); // NOI18N
        txtpassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Penduduk");
        setLocation(new java.awt.Point(350, 80));

        jPanel1.setBackground(new java.awt.Color(0, 0, 54));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Logo.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        Keluarga.setFont(new java.awt.Font("Futura Bk BT", 0, 64)); // NOI18N
        Keluarga.setForeground(new java.awt.Color(255, 255, 255));
        Keluarga.setText("Keluarga");
        jPanel1.add(Keluarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, -1, -1));

        Informasi.setFont(new java.awt.Font("Futura Bk BT", 0, 64)); // NOI18N
        Informasi.setForeground(new java.awt.Color(255, 255, 255));
        Informasi.setText("Informasi");
        jPanel1.add(Informasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        Btn_Regis.setBackground(new java.awt.Color(39, 174, 96));
        Btn_Regis.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Btn_Regis.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Regis.setText("Daftar");
        Btn_Regis.setBorder(null);
        Btn_Regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegisActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 350, 80));

        User_Field.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        User_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        User_Field.setBorder(null);
        User_Field.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(User_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 410, 60));

        Pass_Field.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        Pass_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pass_Field.setBorder(null);
        jPanel1.add(Pass_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 410, 60));

        PassConf_Field.setFont(new java.awt.Font("Anonymous Pro", 0, 24)); // NOI18N
        PassConf_Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PassConf_Field.setBorder(null);
        PassConf_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassConf_FieldActionPerformed(evt);
            }
        });
        jPanel1.add(PassConf_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 270, 410, 60));

        Lbl_Masuk.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Lbl_Masuk.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Masuk.setText("Masuk");
        Lbl_Masuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lbl_MasukMouseClicked(evt);
            }
        });
        jPanel1.add(Lbl_Masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 600, -1, -1));

        Ulang_password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Ulang_password.setForeground(new java.awt.Color(255, 255, 255));
        Ulang_password.setText("Ulang Password");
        jPanel1.add(Ulang_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, -1, -1));

        username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username");
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 110, -1, -1));

        password.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, -1, -1));

        belumpunyaakun.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        belumpunyaakun.setForeground(new java.awt.Color(255, 255, 255));
        belumpunyaakun.setText("Sudah punya akun?");
        jPanel1.add(belumpunyaakun, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 600, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BackGround_Kota.png"))); // NOI18N
        jPanel1.add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_RegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegisActionPerformed
        boolean same = Arrays.equals(Pass_Field.getPassword(), PassConf_Field.getPassword());  //MENDEKLARASIKAN BOOLEAN UNTUK KONDISI PASSWORD DAN ULANG PASSWORD SAMA
        boolean notsame = !same;                                                               //MENDEKLARASIKAN BOOLEAN UNTUK KONDISI PASSWORD DAN ULANG PASSWORD TIDAK SAMA
      
            if (User_Field.getText().equals("")                                                 //PERCABANGAN JIKA TEXTFIELD USER KOSONG
                    || User_Field.getText().equals("")                                          //PERCABANGAN JIKA TEXTFIELD NAMA KOSONG
                    || String.valueOf(Pass_Field.getPassword()).equals("")                      //PERCABANGAN JIKA TEXTFIELD PASSWORD KOSONG
                    || String.valueOf(PassConf_Field.getPassword()).equals(""))                 //PERCABANGAN JIKA TEXTFIELD ULANG PASSWORD KOSONG
            {
                JOptionPane.showMessageDialog(this, "Data tidak boleh kosong", "error", JOptionPane.ERROR_MESSAGE);     //AKAN KELUAR TAMPILAN JOPTION ERROR
                empty_data();                                                                  //MENGKOSONGKAN SEMUA TEXTFIELD
            } else if (same) {                                                                  //PERCABANGAN JIKA PASSWORD DAN ULANG PASSWORD SAMA
                data.setUsername(User_Field.getText());
                data.setPassword(Pass_Field.getText());
                data.simpan();     
                empty_data();
            } else if (notsame) {                                                                   //JIKA PASSWORD DAN ULANG PASSWORD TIDAK SAMA
                JOptionPane.showMessageDialog                                                       //MENAMPILKAN JOPTIONMESSAGE
                        (this, "Password doesn't match", "error", JOptionPane.ERROR_MESSAGE);       //BERISI PASSWORD DOESN'T MATCH
                PassConf_Field.setText("");                                                           //TEXTFIELD ULANG PASSWORD AKAN DI KOSONGI
            }

        
    }//GEN-LAST:event_Btn_RegisActionPerformed

    private void Lbl_MasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lbl_MasukMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new ui.welcome.login().setVisible(true);
    }//GEN-LAST:event_Lbl_MasukMouseClicked

    private void PassConf_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassConf_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassConf_FieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton Btn_Regis;
    private javax.swing.JLabel Informasi;
    private javax.swing.JLabel Keluarga;
    private javax.swing.JLabel Lbl_Masuk;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField PassConf_Field;
    private javax.swing.JPasswordField Pass_Field;
    private javax.swing.JLabel Ulang_password;
    private javax.swing.JTextField User_Field;
    private javax.swing.JLabel belumpunyaakun;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
